# Generated by Django 5.0.6 on 2024-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
